//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DHS.EQUIPMENT.Common {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StrLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StrLang() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DHS.EQUIPMENT.Common.StrLang", typeof(StrLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   IR/OCV과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AMSSTART {
            get {
                return ResourceManager.GetString("AMSSTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STOP과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AMSSTOP {
            get {
                return ResourceManager.GetString("AMSSTOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AUTO과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AUTO {
            get {
                return ResourceManager.GetString("AUTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   START과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BTNMSASTART {
            get {
                return ResourceManager.GetString("BTNMSASTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STOP과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BTNMSASTOP {
            get {
                return ResourceManager.GetString("BTNMSASTOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   APPLY과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BTNOFFSETAPPLY {
            get {
                return ResourceManager.GetString("BTNOFFSETAPPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OPEN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BTNOFFSETOPEN {
            get {
                return ResourceManager.GetString("BTNOFFSETOPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SAVE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BTNOFFSETSAVE {
            get {
                return ResourceManager.GetString("BTNOFFSETSAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ALL OFFSET과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BTNOFFSETSTART {
            get {
                return ResourceManager.GetString("BTNOFFSETSTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STOP과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BTNOFFSETSTOP {
            get {
                return ResourceManager.GetString("BTNOFFSETSTOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SAVE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BTNSAVEDATA {
            get {
                return ResourceManager.GetString("BTNSAVEDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TRAY DOWN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BTNTRAYDOWN {
            get {
                return ResourceManager.GetString("BTNTRAYDOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TRAY UP과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BTNTRAYUP {
            get {
                return ResourceManager.GetString("BTNTRAYUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CONFIG과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CONFIG {
            get {
                return ResourceManager.GetString("CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Init Data과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string INITDATA {
            get {
                return ResourceManager.GetString("INITDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initialize과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Initialize {
            get {
                return ResourceManager.GetString("Initialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IR/OCV is not connected.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string IROCVCONNECTION {
            get {
                return ResourceManager.GetString("IROCVCONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IR/OCV is Manual Mode.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string IROCVMANUALMODE {
            get {
                return ResourceManager.GetString("IROCVMANUALMODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to reset IR/OCV?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string IROCVRESETMSG {
            get {
                return ResourceManager.GetString("IROCVRESETMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RESET IR/OCV과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string IROCVRESETTITLE {
            get {
                return ResourceManager.GetString("IROCVRESETTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   REPLY ← MES과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LBLDATAREPLY {
            get {
                return ResourceManager.GetString("LBLDATAREPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DATA → MES과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LBLDATAUPLOAD {
            get {
                return ResourceManager.GetString("LBLDATAUPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ERROR CODE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LBLERRORCODE {
            get {
                return ResourceManager.GetString("LBLERRORCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ERROR MESSAGE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LBLERRORMESSAGE {
            get {
                return ResourceManager.GetString("LBLERRORMESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IR RANGE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LBLIRRANGE {
            get {
                return ResourceManager.GetString("LBLIRRANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IR SPEC과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LBLIRREMEASURE {
            get {
                return ResourceManager.GetString("LBLIRREMEASURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MANUAL과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LBLMANUALTITLE {
            get {
                return ResourceManager.GetString("LBLMANUALTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OCV RANGE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LBLOCVRANGE {
            get {
                return ResourceManager.GetString("LBLOCVRANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OCV SPEC과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LBLOCVREMEASURE {
            get {
                return ResourceManager.GetString("LBLOCVREMEASURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CHANNEL과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LBLOFFSETCHANNEL {
            get {
                return ResourceManager.GetString("LBLOFFSETCHANNEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Repeat Count과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LBLOFFSETREPEATCOUNT {
            get {
                return ResourceManager.GetString("LBLOFFSETREPEATCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STATUS CODE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LBLPROCESS {
            get {
                return ResourceManager.GetString("LBLPROCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RECIPE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LBLRECIPE {
            get {
                return ResourceManager.GetString("LBLRECIPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TRAY INFO ← MES과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LBLREPLYTRAYINFO {
            get {
                return ResourceManager.GetString("LBLREPLYTRAYINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TRAY ID → MES과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LBLREQUESTTRAYINFO {
            get {
                return ResourceManager.GetString("LBLREQUESTTRAYINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STATUS과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LBLSTATUS {
            get {
                return ResourceManager.GetString("LBLSTATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TRAY ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LBLTRAYID {
            get {
                return ResourceManager.GetString("LBLTRAYID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TRAY SETTING과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LBLTRAYSETTING {
            get {
                return ResourceManager.GetString("LBLTRAYSETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IR/OCV INSPECTION 2024 06 11과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MAINTITLE {
            get {
                return ResourceManager.GetString("MAINTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MANUAL과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANUAL {
            get {
                return ResourceManager.GetString("MANUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MANUAL MODE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANUALMODE {
            get {
                return ResourceManager.GetString("MANUALMODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MES is not connected과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MESCONNECTION {
            get {
                return ResourceManager.GetString("MESCONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NG Info.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NGINFO {
            get {
                return ResourceManager.GetString("NGINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are more than 1 zero value in measure field.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OFFSETAPPLYMSG {
            get {
                return ResourceManager.GetString("OFFSETAPPLYMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply offset Error.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OFFSETAPPLYTITLE {
            get {
                return ResourceManager.GetString("OFFSETAPPLYTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PLC is not connected과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PLCCONNECTION {
            get {
                return ResourceManager.GetString("PLCCONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PLC is error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PLCERROR {
            get {
                return ResourceManager.GetString("PLCERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PLC is Manual Mode과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PLCMANUALMODE {
            get {
                return ResourceManager.GetString("PLCMANUALMODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BARCODE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PNLBARCODE {
            get {
                return ResourceManager.GetString("PNLBARCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FINISH과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PNLFINISH {
            get {
                return ResourceManager.GetString("PNLFINISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MEASURE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PNLMEASURE {
            get {
                return ResourceManager.GetString("PNLMEASURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IR/OCV Measuring Values과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PNLMEASURINGTITLE {
            get {
                return ResourceManager.GetString("PNLMEASURINGTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   READY과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PNLREADY {
            get {
                return ResourceManager.GetString("PNLREADY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TRAY DOWN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PNLTRAYDOWN {
            get {
                return ResourceManager.GetString("PNLTRAYDOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TRAY IN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PNLTRAYIN {
            get {
                return ResourceManager.GetString("PNLTRAYIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TRAY OUT과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PNLTRAYOUT {
            get {
                return ResourceManager.GetString("PNLTRAYOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TRAY UP과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PNLTRAYUP {
            get {
                return ResourceManager.GetString("PNLTRAYUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   INIT과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RESET {
            get {
                return ResourceManager.GetString("RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IR/OCV Measurement is finish.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STEPEND {
            get {
                return ResourceManager.GetString("STEPEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IR/OCV is runnig.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STEPRUNNING {
            get {
                return ResourceManager.GetString("STEPRUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IR/OCV Tray In.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STEPTRAYIN {
            get {
                return ResourceManager.GetString("STEPTRAYIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IR/OCV Tray Out.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STEPTRAYOUT {
            get {
                return ResourceManager.GetString("STEPTRAYOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IR/OCV Tray Up.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STEPTRAYUP {
            get {
                return ResourceManager.GetString("STEPTRAYUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IR/OCV is ready.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STEPVACANCY {
            get {
                return ResourceManager.GetString("STEPVACANCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tray Out과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TRAYOUT {
            get {
                return ResourceManager.GetString("TRAYOUT", resourceCulture);
            }
        }
    }
}
