//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DHS.EQUIPMENT.Common {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StrLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StrLang() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DHS.EQUIPMENT.Common.StrLang", typeof(StrLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   AUTO과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AUTO {
            get {
                return ResourceManager.GetString("AUTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CONFIG과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CONFIG {
            get {
                return ResourceManager.GetString("CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initialize과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Initialize {
            get {
                return ResourceManager.GetString("Initialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MANUAL과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANUAL {
            get {
                return ResourceManager.GetString("MANUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NG Info.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NGINFO {
            get {
                return ResourceManager.GetString("NGINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BARCODE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PNLBARCODE {
            get {
                return ResourceManager.GetString("PNLBARCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FINISH과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PNLFINISH {
            get {
                return ResourceManager.GetString("PNLFINISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MEASURE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PNLMEASURE {
            get {
                return ResourceManager.GetString("PNLMEASURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   READY과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PNLREADY {
            get {
                return ResourceManager.GetString("PNLREADY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TRAY DOWN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PNLTRAYDOWN {
            get {
                return ResourceManager.GetString("PNLTRAYDOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TRAY IN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PNLTRAYIN {
            get {
                return ResourceManager.GetString("PNLTRAYIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TRAY OUT과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PNLTRAYOUT {
            get {
                return ResourceManager.GetString("PNLTRAYOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TRAY UP과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PNLTRAYUP {
            get {
                return ResourceManager.GetString("PNLTRAYUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RESET과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RESET {
            get {
                return ResourceManager.GetString("RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tray Out과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TRAYOUT {
            get {
                return ResourceManager.GetString("TRAYOUT", resourceCulture);
            }
        }
    }
}
